#Jekyll configuration
name: Scientific communication materials
title: TITLE
description: Resources to help students publishing in JEI
url: "https://juanramonmtz.github.io"
markdown: GFM
theme: jekyll-theme-slate
